Repository 4ragrant/SCENTASY_BE, pull requests merged in 2024-08, with the labels that each got.

#10 🔨 Refactor: #9 refactor for deploy
  src/main/java/fouragrant/scentasy/config/SecurityConfig.java
  src/main/java/fouragrant/scentasy/config/SwaggerConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/fouragrant/scentasy/ScentasyApplicationTests.java
Labels: bug

#16 fix: cors 관련 corsConfig파일 수정
  src/main/java/fouragrant/scentasy/config/CorsConfig.java
Labels: bug, 🌏 Deploy, 📬 API, ☁️ narong

#22 ✨ Feature: #7 feature chat
  src/main/java/fouragrant/scentasy/biz/chat/controller/ChatController.java
  src/main/java/fouragrant/scentasy/biz/chat/domain/Chat.java
  src/main/java/fouragrant/scentasy/biz/chat/dto/ChatReqDto.java
  src/main/java/fouragrant/scentasy/biz/chat/dto/ChatResDto.java
  src/main/java/fouragrant/scentasy/biz/chat/repository/ChatRepository.java
  src/main/java/fouragrant/scentasy/biz/chat/service/ChatService.java
  src/main/java/fouragrant/scentasy/biz/member/CustomUserDetails.java
  src/main/java/fouragrant/scentasy/biz/member/domain/ExtraInfo.java
  src/main/java/fouragrant/scentasy/biz/member/domain/Member.java
  src/main/java/fouragrant/scentasy/biz/member/service/CustomUserDetailsService.java
  src/main/java/fouragrant/scentasy/config/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ✨ Feature, ☁️ narong

#24 ✨ Feature: #7 feature chat retrieve
  src/main/java/fouragrant/scentasy/biz/chat/controller/ChatController.java
  src/main/java/fouragrant/scentasy/biz/chat/dto/ChatListResDto.java
  src/main/java/fouragrant/scentasy/biz/chat/repository/ChatRepository.java
  src/main/java/fouragrant/scentasy/biz/chat/service/ChatService.java
Labels: ✨ Feature, ☁️ narong

#25 🔨 Refactor: #20 swagger setting for auth
  src/main/java/fouragrant/scentasy/biz/member/cotroller/AuthController.java
  src/main/java/fouragrant/scentasy/biz/member/cotroller/ExtraInfoController.java
Labels: 📃 Docs, ☁️ narong

#26 ✨ Feature: #7 feature chat with extra info
  src/main/java/fouragrant/scentasy/biz/chat/dto/ChatReqDto.java
  src/main/java/fouragrant/scentasy/biz/chat/service/ChatService.java
  src/main/java/fouragrant/scentasy/biz/member/domain/ExtraInfo.java
  src/main/java/fouragrant/scentasy/biz/member/domain/Member.java
  src/main/java/fouragrant/scentasy/biz/member/service/ExtraInfoService.java
Labels: 🔨 Refactor, ☁️ narong

#29 🔨 fix: 로그인 시 멤버의 추가정보 조회 불일치 에러 해결
  src/main/java/fouragrant/scentasy/biz/member/service/AuthService.java
Labels: bug, ☁️ narong

#31 🔨 fix: 로그인 시 응답 에러 해결
  src/main/java/fouragrant/scentasy/biz/member/service/AuthService.java
Labels: bug, 🔨 Refactor, :ribbon: kayeon

#32 🔨 fix: 스웨거 cors 해결
  src/main/java/fouragrant/scentasy/config/CorsConfig.java
Labels: 🌏 Deploy, 📬 API, ☁️ narong
