Repository 4ragrant/SCENTASY_BE, pull requests merged in 2024-10, with the labels that each got.

#54 ✨ Feature: #36 마이페이지 관련 기능 구현
  build.gradle
  src/main/java/fouragrant/scentasy/biz/member/cotroller/ExtraInfoController.java
  src/main/java/fouragrant/scentasy/biz/member/dto/ExtraInfoResDto.java
  src/main/java/fouragrant/scentasy/biz/member/repository/ExtraInfoRepository.java
  src/main/java/fouragrant/scentasy/biz/member/service/ExtraInfoService.java
  src/main/java/fouragrant/scentasy/biz/member/service/MemberService.java
  src/main/java/fouragrant/scentasy/biz/mypage/controller/MypageController.java
  src/main/java/fouragrant/scentasy/biz/mypage/controller/S3Controller.java
  src/main/java/fouragrant/scentasy/biz/mypage/service/S3Service.java
  src/main/java/fouragrant/scentasy/common/exception/ErrorCode.java
  src/main/java/fouragrant/scentasy/config/S3Config.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: ✨ Feature, 📬 API, ⚙ Setting, :ribbon: kayeon

#56 🔨 Fix: #35 향수 관련 토큰 인증 설정
  src/main/java/fouragrant/scentasy/biz/member/service/CustomUserDetailsService.java
  src/main/java/fouragrant/scentasy/biz/perfume/controller/PerfumeController.java
  src/main/java/fouragrant/scentasy/biz/perfume/service/PerfumeService.java
  src/main/java/fouragrant/scentasy/config/SecurityConfig.java
  src/main/java/fouragrant/scentasy/jwt/TokenProvider.java
  src/main/resources/application.yml
Labels: bug, 🔨 Refactor, :ribbon: kayeon

#59 ✨ Feature: #57 향수 레시피 생성 구현
  src/main/java/fouragrant/scentasy/biz/chat/service/ChatService.java
  src/main/java/fouragrant/scentasy/biz/member/domain/Scent.java
  src/main/java/fouragrant/scentasy/biz/perfume/controller/PerfumeController.java
  src/main/java/fouragrant/scentasy/biz/perfume/domain/Perfume.java
  src/main/java/fouragrant/scentasy/biz/perfume/dto/PerfumeDto.java
  src/main/java/fouragrant/scentasy/biz/perfume/dto/PerfumeRecipeReqDto.java
  src/main/java/fouragrant/scentasy/biz/perfume/dto/PerfumeRecipeResDto.java
  src/main/java/fouragrant/scentasy/biz/perfume/service/PerfumeRecipeService.java
  src/main/java/fouragrant/scentasy/biz/perfume/service/PerfumeService.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📬 API, ☁️ narong

#60 ✨ Feat: tcp 통신 테스트 구현
  src/main/java/fouragrant/scentasy/tcp/TcpTestController.java
Labels: 🌏 Deploy, ✨ Feature, 📬 API, ☁️ narong

#62 ✨ Feature: tcp 통신을 통한 perfume 제작 기능 구현
  src/main/java/fouragrant/scentasy/biz/perfume/controller/PerfumeDeviceController.java
  src/main/java/fouragrant/scentasy/biz/perfume/repository/PerfumeRepository.java
  src/main/java/fouragrant/scentasy/biz/perfume/service/PerfumeDeviceService.java
Labels: ✨ Feature, 📬 API, ☁️ narong

#63 ✨ Feature: #35 향수 정보 플라스크 연결 및 반환값 변경
  src/main/java/fouragrant/scentasy/biz/perfume/controller/PerfumeController.java
  src/main/java/fouragrant/scentasy/biz/perfume/domain/Accord.java
  src/main/java/fouragrant/scentasy/biz/perfume/domain/Perfume.java
  src/main/java/fouragrant/scentasy/biz/perfume/dto/FlaskResponse.java
  src/main/java/fouragrant/scentasy/biz/perfume/dto/PerfumeDto.java
  src/main/java/fouragrant/scentasy/biz/perfume/dto/PerfumeRecipeResDto.java
  src/main/java/fouragrant/scentasy/biz/perfume/service/PerfumeRecipeService.java
  src/main/java/fouragrant/scentasy/biz/perfume/service/PerfumeService.java
Labels: ✨ Feature, 📬 API, :ribbon: kayeon

#65 🛠️ Refactor: 향수 레시피 DTO 향수 생성 날짜 추가
  src/main/java/fouragrant/scentasy/biz/perfume/dto/PerfumeRecipeResDto.java
  src/main/java/fouragrant/scentasy/biz/perfume/service/PerfumeRecipeService.java
Labels: 🔨 Refactor, :ribbon: kayeon

#69 🔨 Refactor: 채팅 세션 id의 형식 변경 및 스웨거 수정 작업
  src/main/java/fouragrant/scentasy/ScentasyApplication.java
  src/main/java/fouragrant/scentasy/biz/chat/controller/ChatController.java
  src/main/java/fouragrant/scentasy/biz/chat/service/ChatService.java
  src/main/java/fouragrant/scentasy/config/CorsConfig.java
  src/main/java/fouragrant/scentasy/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: 🔨 Refactor, ☁️ narong
